#ifndef PROGRAM_COMMANDS_INCLUDED
#define PROGRAM_COMMANDS_INCLUDED


#include <types.c>


typedef enum
{
	IMMEDIATE_DATA_COMMAND,

	JUMP_COMMAND,

	CALL_IMMEDIATE_COMMAND,
	CALL_COMMAND,
	BEGIN_SUBPROGRAM_COMMAND,
	RETURN_COMMAND,
	SAVE_RETURNED_CONTEXT_COMMAND,
	//UNION_RETURN_COMMAND,

	SET_LOCAL_CONTEXT_COMMAND,
	GET_LOCAL_CONTEXT_COMMAND,

	SET_GLOBAL_CONTEXT_COMMAND,
	GET_GLOBAL_CONTEXT_COMMAND,

	//зависящие от размера комманды
	PUSH_COMMAND,
	POP_COMMAND,

	SET_LOCAL_COMMAND,
	GET_LOCAL_COMMAND,

	SET_GLOBAL_COMMAND,
	GET_GLOBAL_COMMAND,

	STORE_COMMAND,
	LOAD_COMMAND,

	JUMP_IF_ZERO_COMMAND,
	JUMP_IF_NOT_ZERO_COMMAND,

	NOT_COMMAND,
	NEGATE_COMMAND,

	OR_COMMAND,
	AND_COMMAND,
	XOR_COMMAND,

	SHIFT_LEFT_COMMAND,
	SHIFT_RIGHT_COMMAND,

	ADD_COMMAND,
	SUBTRACT_COMMAND,
	MULTIPLY_COMMAND,
	DIVIDE_COMMAND,
	MODULO_COMMAND,

	EQUAL_COMMAND,
	NOT_EQUAL_COMMAND,
	LESSER_COMMAND,
	LESSER_OR_EQUAL_COMMAND,
	GREATER_COMMAND,
	GREATER_OR_EQUAL_COMMAND,


	STOP_COMMAND = 255
}
Commands;


// 12 не зависящих от размера комманд
// 28 зависящих от размера комманд

#endif//PROGRAM_COMMANDS_INCLUDED